version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../../laravel:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ../..
      dockerfile: ./.deploy/local/php/Dockerfile
    volumes:
      - ../../laravel:/app
    entrypoint: [ "/bin/sh", "-c", "php artisan storage:link && /usr/bin/supervisord -c /etc/supervisor/supervisord.conf" ]
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: elissa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
